# Generated by Django 5.2.7 on 2026-03-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('length_m__gt', 0)), name='cable_length_gt_0'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='cable_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('SWITCH', 'Коммутатор'), ('PC', 'ПК'), ('ROUTER', 'Роутер')], max_length=16)),
                ('ports_count', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ports_count__gte', 1)), name='device_type_ports_gte_1'), models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='device_type_width_gt_0'), models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='device_type_height_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='network.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('index', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='network.device')),
            ],
            options={
                'ordering': ['device_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='network.cable')),
                ('port_a', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='link_as_a', to='network.port')),
                ('port_b', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='link_as_b', to='network.port')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='network.building')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='network.room'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('device', 'index'), name='unique_port_index_per_device'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_port_name_per_device'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(condition=models.Q(('port_a', models.F('port_b')), _negated=True), name='link_ports_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_room_name_in_building'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='room_width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='room_height_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_device_name_in_room'),
        ),
    ]
