# Generated by Django 5.2.7 on 2026-03-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='port_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_a', to='network.port'),
        ),
        migrations.AlterField(
            model_name='link',
            name='port_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_b', to='network.port'),
        ),
    ]
