# Generated by Django 5.2.7 on 2026-04-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_link_port_a_alter_link_port_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_connected_devices', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'computer',
                'verbose_name_plural': 'computers',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_connected_devices', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'router',
                'verbose_name_plural': 'routers',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_connected_devices', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'switch',
                'verbose_name_plural': 'switches',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='cable',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='cable',
            name='cable_length_gt_0',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='length_m',
        ),
        migrations.AddField(
            model_name='cable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cables/'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='network_computer_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.CheckConstraint(condition=models.Q(('max_connected_devices__isnull', True), ('max_connected_devices__gte', 1), _connector='OR'), name='network_computer_max_connected_devices_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='network_router_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.CheckConstraint(condition=models.Q(('max_connected_devices__isnull', True), ('max_connected_devices__gte', 1), _connector='OR'), name='network_router_max_connected_devices_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='switch',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='network_switch_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='switch',
            constraint=models.CheckConstraint(condition=models.Q(('max_connected_devices__isnull', True), ('max_connected_devices__gte', 1), _connector='OR'), name='network_switch_max_connected_devices_gte_1'),
        ),
        migrations.AddField(
            model_name='topologydevice',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topology_devices', to='network.computer'),
        ),
        migrations.AddField(
            model_name='topologydevice',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topology_devices', to='network.router'),
        ),
        migrations.AddField(
            model_name='topologydevice',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topology_devices', to='network.switch'),
        ),
        migrations.AlterField(
            model_name='port',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='network.topologydevice'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddConstraint(
            model_name='topologydevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('computer__isnull', False), ('router__isnull', True), ('switch__isnull', True)), models.Q(('computer__isnull', True), ('router__isnull', True), ('switch__isnull', False)), models.Q(('computer__isnull', True), ('router__isnull', False), ('switch__isnull', True)), _connector='OR'), name='topology_device_exactly_one_catalog_item'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
